# Generated by Django 2.1.1 on 2018-10-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haxtor', '0002_auto_20181026_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCat',
            field=models.CharField(choices=[('1', 'kids'), ('2', 'coder')], max_length=254, null=True),
        ),
    ]
