# Generated by Django 2.1.1 on 2018-10-26 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haxtor', '0004_auto_20181026_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('userCat', models.CharField(choices=[('1', 'kids'), ('2', 'coder')], max_length=254)),
                ('point', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprog',
            name='uID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
