# Generated by Django 2.0.9 on 2018-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haxtor', '0005_auto_20181026_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quesLevel',
            field=models.CharField(choices=[('1', 'easy'), ('2', 'medium'), ('3', 'hard')], max_length=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='diffLevel',
            field=models.CharField(choices=[('1', 'easy'), ('2', 'medium'), ('3', 'hard')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprog',
            name='currEvolution',
            field=models.CharField(choices=[('1', 'CupCake'), ('2', 'Pasterie'), ('3', 'FudgeCake')], max_length=50),
        ),
    ]
